メッセージの非同期通信
yanagitani11/Chatspace pull request #4
Opened 2019-01-09 17:13 UTC by yanagitani11

# WHAT
チャットの画面にてメッセージを送信すると非同期で画面が更新される
# WHY
ux向上のため

2019-01-11 08:57 UTC, kuroko918 commented on chat-space/app/assets/javascripts/messages.js
> +$(function() {
この記述は1行目にあるので不要です！

2019-01-11 08:57 UTC, kuroko918 commented on chat-space/app/controllers/messages_controller.rb
> +    else @message.nill?
elseの書き方が正しくありません。条件を付けるならelsifです！

2019-01-11 08:57 UTC, kuroko918 commented on chat-space/app/views/messages/create.json.jbuilder
> +
この空行は消しておきましょう！

2019-01-11 13:18 UTC, yanagitani11 commented on chat-space/app/assets/javascripts/messages.js
> +$(function() {
修正しました。

2019-01-11 13:18 UTC, yanagitani11 commented on chat-space/app/controllers/messages_controller.rb
> +    else @message.nill?
修正しました。

2019-01-11 13:19 UTC, yanagitani11 commented on chat-space/app/views/messages/create.json.jbuilder
> +
消しました。

2019-01-12 01:26 UTC, kuroko918 commented on chat-space/app/controllers/messages_controller.rb
> +    elsif @message.nill?
こちら申し訳ないのですが、`else`だけにして、@messageがsave出来なかった場合を記述したほうがいいかと思います！

2019-01-12 01:26 UTC, kuroko918 commented on chat-space/app/assets/javascripts/messages.js
> +			disabled: false,
こちらは必要ですか？

2019-01-13 03:42 UTC, yanagitani11 commented on chat-space/app/controllers/messages_controller.rb
> +    elsif @message.nill?
修正しました

2019-01-13 03:42 UTC, yanagitani11 commented on chat-space/app/assets/javascripts/messages.js
> +			disabled: false,
いらないですね！消し忘れておりました。
修正しました。

2019-01-13 03:46 UTC, ghost requested changes

2019-01-13 03:46 UTC, hiroki5123 commented on chat-space/app/assets/javascripts/messages.js
> +      		var html = buildHTML(data);
インデント一個奥です！

2019-01-13 03:46 UTC, hiroki5123 commented on chat-space/app/controllers/messages_controller.rb
> +    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
```user_id: current_user```
でいける気がします

2019-01-13 03:46 UTC, hiroki5123 commented on chat-space/app/controllers/messages_controller.rb
> +    @group_users = @group.users
set_groupというメソッド名なので、
userを取得するのは少し違和感を感じます。
もし可能なら ```set_users``` というメソッドを作成して、そちらでuserを取得してください。

2019-01-13 04:20 UTC, yanagitani11 commented on chat-space/app/assets/javascripts/messages.js
> +      		var html = buildHTML(data);
修正しました

2019-01-13 04:20 UTC, yanagitani11 commented on chat-space/app/controllers/messages_controller.rb
> +    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
ありがとうございます。修正しました。

2019-01-13 04:20 UTC, yanagitani11 commented on chat-space/app/controllers/messages_controller.rb
> +    @group_users = @group.users
set_users で定義し直しました。

2019-01-13 04:39 UTC, kuroko918 commented on chat-space/app/controllers/messages_controller.rb
> +    params.require(:message).permit(:content, :image).merge(user_id: current_user)
確認だけしていただきたいのですが、きちんとuser_idが入ってたら、マージして次に行きましょう！

2019-01-14 01:03 UTC, merged